name: shamor_vezachor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  provider: ^6.0.5 # ודא שהגרסה תואמת את שלך, אם שונה
  shared_preferences: ^2.2.0 # ודא שהגרסה תואמת את שלך, אם שונה
  path_provider: ^2.1.1 # ודא שהגרסה תואמת את שלך, אם שונה
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # הוספת החבילה

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/app_icon.png" # עדכן אם שם הקובץ או הנתיב שונים
  min_sdk_android: 21 # אופציונלי, התאם ל-minSdk שלך
  web:
    generate: true
    image_path: "assets/launcher_icon/app_icon.png" # עדכן אם שם הקובץ או הנתיב שונים
    background_color: "#0175C2" # התאם לצבע הרקע שלך מה-manifest.json
    theme_color: "#0175C2" # התאם לצבע ה-theme שלך מה-manifest.json
  windows:
    generate: true
    image_path: "assets/launcher_icon/app_icon.png" # עדכן אם שם הקובץ או הנתיב שונים
    icon_size: 48 # ניתן לבחור גדלים שונים
  macos:
    generate: true
    image_path: "assets/launcher_icon/app_icon.png" # עדכן אם שם הקובץ או הנתיב שונים

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/launcher_icon/ # הוספת הנתיב לאייקון ה-launcher
    - assets/images/ # הוספת הנתיב לתמונות בתוך האפליקציה