name: Build Flet Windows App

on:
  push:
    branches:
      - flet-build

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'
          channel: 'stable'

      - name: Verify Flutter Installation
        run: flutter doctor

      - name: Build Flet Windows App
        run: |
          flet build windows --output build/windows -v
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: 1  # מכריח שימוש ב-UTF-8 כברירת מחדל

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet_windows_app
          path: build/windows/*
